### ISSUE TITLE
@Arg does not add definition to schema

### ISSUE THREAD

**Issue by ebenoist** [google/rejoiner#23]
An `@Arg` annotation is not enough to add the specified proto definition to the GraphQL schema and will result in a runtime error if not referenced elsewhere.

Given the example:
```JAVA
  @Query("getNegotiation")
  ListenableFuture<NegotiationsResponse> getNegotiation(NegotiationsRequest request,
      CoreClient client, @Arg("token") AuthToken token) {

    return client.getNegotiation(request.getId(), token.getToken());
  }
```

Where AuthToken is in a different proto definition tree and not returned by any queries, the following will result:

```
1) Error in custom provider, graphql.AssertException: type Input_rql_AuthToken not found in schema
  while locating com.google.api.graphql.rejoiner.SchemaProviderModule$SchemaImpl
  while locating graphql.schema.GraphQLSchema annotated with interface com.google.api.graphql.rejoiner.Schema

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at com.reverb.rql.RQLHander.<clinit>(RQLHander.java:44)
	... 1 more
Caused by: graphql.AssertException: type Input_rql_AuthToken not found in schema
	at graphql.Assert.assertTrue(Assert.java:37)
	at graphql.schema.SchemaUtil.resolveTypeReference(SchemaUtil.java:221)
	at graphql.schema.GraphQLArgument.replaceTypeReferences(GraphQLArgument.java:48)
	at graphql.schema.SchemaUtil.resolveTypeReferencesForFieldsContainer(SchemaUtil.java:207)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:189)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:238)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:231)
	at com.google.api.graphql.rejoiner.SchemaProviderModule$SchemaImpl.get(SchemaProviderModule.java:91)
	at com.google.api.graphql.rejoiner.SchemaProviderModule$SchemaImpl.get(SchemaProviderModule.java:36)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 3 more
```

If I add a "fake" query that returns the token.

```JAVA
  @Query("tokenRequest")
  AuthToken getToken(AuthToken token) {
    return token;
  }
```

The proto def is discovered and converted into a type for the GraphQL Schema.

**Comment by siderakis** [comment]
Thanks for reporting this bug, is should be been fixed now.
